// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package modulev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ModuleQueryServiceClient is the client API for ModuleQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModuleQueryServiceClient interface {
	// Get queries the Balance table by its primary key.
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	// ListBalance queries the Balance table using prefix and range queries against defined indexes.
	ListBalance(ctx context.Context, in *ListBalanceRequest, opts ...grpc.CallOption) (*ListBalanceResponse, error)
	// Get queries the Supply table by its primary key.
	GetSupply(ctx context.Context, in *GetSupplyRequest, opts ...grpc.CallOption) (*GetSupplyResponse, error)
	// ListSupply queries the Supply table using prefix and range queries against defined indexes.
	ListSupply(ctx context.Context, in *ListSupplyRequest, opts ...grpc.CallOption) (*ListSupplyResponse, error)
}

type moduleQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModuleQueryServiceClient(cc grpc.ClientConnInterface) ModuleQueryServiceClient {
	return &moduleQueryServiceClient{cc}
}

func (c *moduleQueryServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, "/sonrhq.service.module.v1.ModuleQueryService/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleQueryServiceClient) ListBalance(ctx context.Context, in *ListBalanceRequest, opts ...grpc.CallOption) (*ListBalanceResponse, error) {
	out := new(ListBalanceResponse)
	err := c.cc.Invoke(ctx, "/sonrhq.service.module.v1.ModuleQueryService/ListBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleQueryServiceClient) GetSupply(ctx context.Context, in *GetSupplyRequest, opts ...grpc.CallOption) (*GetSupplyResponse, error) {
	out := new(GetSupplyResponse)
	err := c.cc.Invoke(ctx, "/sonrhq.service.module.v1.ModuleQueryService/GetSupply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleQueryServiceClient) ListSupply(ctx context.Context, in *ListSupplyRequest, opts ...grpc.CallOption) (*ListSupplyResponse, error) {
	out := new(ListSupplyResponse)
	err := c.cc.Invoke(ctx, "/sonrhq.service.module.v1.ModuleQueryService/ListSupply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModuleQueryServiceServer is the server API for ModuleQueryService service.
// All implementations must embed UnimplementedModuleQueryServiceServer
// for forward compatibility
type ModuleQueryServiceServer interface {
	// Get queries the Balance table by its primary key.
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	// ListBalance queries the Balance table using prefix and range queries against defined indexes.
	ListBalance(context.Context, *ListBalanceRequest) (*ListBalanceResponse, error)
	// Get queries the Supply table by its primary key.
	GetSupply(context.Context, *GetSupplyRequest) (*GetSupplyResponse, error)
	// ListSupply queries the Supply table using prefix and range queries against defined indexes.
	ListSupply(context.Context, *ListSupplyRequest) (*ListSupplyResponse, error)
	mustEmbedUnimplementedModuleQueryServiceServer()
}

// UnimplementedModuleQueryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedModuleQueryServiceServer struct {
}

func (UnimplementedModuleQueryServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedModuleQueryServiceServer) ListBalance(context.Context, *ListBalanceRequest) (*ListBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBalance not implemented")
}
func (UnimplementedModuleQueryServiceServer) GetSupply(context.Context, *GetSupplyRequest) (*GetSupplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupply not implemented")
}
func (UnimplementedModuleQueryServiceServer) ListSupply(context.Context, *ListSupplyRequest) (*ListSupplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSupply not implemented")
}
func (UnimplementedModuleQueryServiceServer) mustEmbedUnimplementedModuleQueryServiceServer() {}

// UnsafeModuleQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModuleQueryServiceServer will
// result in compilation errors.
type UnsafeModuleQueryServiceServer interface {
	mustEmbedUnimplementedModuleQueryServiceServer()
}

func RegisterModuleQueryServiceServer(s grpc.ServiceRegistrar, srv ModuleQueryServiceServer) {
	s.RegisterService(&ModuleQueryService_ServiceDesc, srv)
}

func _ModuleQueryService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleQueryServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonrhq.service.module.v1.ModuleQueryService/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleQueryServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleQueryService_ListBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleQueryServiceServer).ListBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonrhq.service.module.v1.ModuleQueryService/ListBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleQueryServiceServer).ListBalance(ctx, req.(*ListBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleQueryService_GetSupply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleQueryServiceServer).GetSupply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonrhq.service.module.v1.ModuleQueryService/GetSupply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleQueryServiceServer).GetSupply(ctx, req.(*GetSupplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleQueryService_ListSupply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSupplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleQueryServiceServer).ListSupply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonrhq.service.module.v1.ModuleQueryService/ListSupply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleQueryServiceServer).ListSupply(ctx, req.(*ListSupplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModuleQueryService_ServiceDesc is the grpc.ServiceDesc for ModuleQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModuleQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sonrhq.service.module.v1.ModuleQueryService",
	HandlerType: (*ModuleQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _ModuleQueryService_GetBalance_Handler,
		},
		{
			MethodName: "ListBalance",
			Handler:    _ModuleQueryService_ListBalance_Handler,
		},
		{
			MethodName: "GetSupply",
			Handler:    _ModuleQueryService_GetSupply_Handler,
		},
		{
			MethodName: "ListSupply",
			Handler:    _ModuleQueryService_ListSupply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sonrhq/service/module/v1/module_query.proto",
}
