name: CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge_group:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
      - run: gh extension install johnmanjiro13/gh-bump
      # Set up Buf
      - uses: bufbuild/buf-setup-action@v1

      # Check for breaking changes with Buf
      - name: Buf Breaking Changes
        uses: bufbuild/buf-breaking-action@v1
        continue-on-error: true
        with:
          input: "proto"
          against: "https://github.com/sonrhq/sonr.git#branch=master"

      # Lint with Buf and capture output
      - name: Buf Lint
        id: buf_lint
        uses: bufbuild/buf-lint-action@v1
        continue-on-error: true
        with:
          input: "proto"

      # Set up Earthly
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.10

      # Test with Earthly
      - name: Run tests
        run: earthly --org sonrhq --sat david --ci +test
