name: CI with Earthly

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2

      # Set up Buf
      - uses: bufbuild/buf-setup-action@v1

      # Check for breaking changes with Buf
      - name: Buf Breaking Changes
        uses: bufbuild/buf-breaking-action@v1
        continue-on-error: true
        with:
          input: "proto"
          against: "https://github.com/sonrhq/sonr.git#branch=master"

      # Lint with Buf and capture output
      - name: Buf Lint
        id: buf_lint
        uses: bufbuild/buf-lint-action@v1
        continue-on-error: true
        with:
          input: "proto"

      # Create issues for linting errors if there are any
      - name: Create lint issues
        if: failure() && steps.buf_lint.outcome == 'failure'
        run: |
          echo "${{ steps.buf_lint.outputs.lint-out }}" | awk '/.proto:[0-9]+:[0-9]+:/ {print $0}' | while IFS= read -r line; do
            title=$(echo "$line" | cut -d':' -f 1,2)
            body=$(echo "$line" | cut -d':' -f 3-)
            gh issue create --title "$title" --body "$body"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Set up Earthly
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.10

      # Test with Earthly
      - name: Run tests
        run: earthly --org sonrhq --sat david --ci +test
